FROM node:20-alpine

WORKDIR /app

# Copy only package.json to install deps
COPY package.json ./

# Install dependencies and winston
RUN npm install && \
    npm install winston @types/winston --save

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
