FROM node:20-alpine

WORKDIR /app

# Copy only package.json to install deps
COPY package.json ./

# Install dependencies (generates package-lock.json)
RUN npm install

# Copy rest of the project
# COPY tsconfig.json ./
# COPY src ./src
# COPY static ./static
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
