apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voice-agent-argocd-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/razachisibrahimah/voice-agent.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: voice-agent 

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true   