apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-logs-pvc
  namespace: voice-agent
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: traefik-logs-pv
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
